//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Colors")
export class ColorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Color_ID: string;

@Column({nullable: true})
Color_Name: string;

@Column({nullable: true})
Color_Code: string;


}
