//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Games")
export class GamesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Game_ID: string;

@Column({nullable: true})
Player_1: string;

@Column({nullable: true})
Player_2: string;

@Column({nullable: true})
Final_Score: string;


}
