//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Lights")
export class LightsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Light_ID: string;

@Column({nullable: true})
Light_Type: string;

@Column({nullable: true})
Color: string;


}
