//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Players")
export class PlayersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Player_Name: string;

@Column({nullable: true})
Wins: string;

@Column({nullable: true})
Losses: string;

@Column({nullable: true})
Draws: string;


}
